#!/usr/bin/env python3
"""
img_to_h.py — converts images/0-5.png to src/outfits.h
Images are scaled to fit 240x320 (portrait), converted to RGB565.
Transparent pixels become white (0xFFFF).

Temperature mapping:
  0 = >78°F   (bikini)
  1 = 69-78°F
  2 = 59-69°F
  3 = 50-58°F
  4 = 39-49°F
  5 = <39°F   (heavy coat)

Usage:
    python3 tools/img_to_h.py
Outputs:
    src/outfits.h
"""

from PIL import Image
from pathlib import Path

SCREEN_W = 320
SCREEN_H = 240
NUM_IMAGES = 6
IMG_DIR = Path(__file__).parent.parent / "images"
OUT_PATH = Path(__file__).parent.parent / "src" / "outfits.h"

# Transparent key color in RGB565 — magenta, not present in these images
TRANSPARENT = 0xF81F  # RGB(255, 0, 255)

# Temperature thresholds in °F (descending), index into image array
THRESHOLDS = [78.8, 69.8, 59.0, 50.0, 39.2]
# 0: >=78.8  1: 69.8-78.7  2: 59-69.7  3: 50-58.9  4: 39.2-49.9  5: <39.2

def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def process_image(path):
    img = Image.open(path).convert("RGBA")
    # Scale to fill full height, preserve aspect ratio
    iw, ih = img.size
    scale = SCREEN_H / ih
    new_w = int(iw * scale)
    new_h = SCREEN_H
    img = img.resize((new_w, new_h), Image.LANCZOS)
    # If still wider than screen, scale down to fit width
    if new_w > SCREEN_W:
        scale2 = SCREEN_W / new_w
        img = img.resize((SCREEN_W, int(new_h * scale2)), Image.LANCZOS)
    w, h = img.size
    # Center on transparent canvas
    canvas = Image.new("RGBA", (SCREEN_W, SCREEN_H), (0, 0, 0, 0))
    x = (SCREEN_W - w) // 2
    y = (SCREEN_H - h) // 2
    canvas.paste(img, (x, y), img)
    result = []
    for r, g, b, a in canvas.getdata():
        if a < 128:
            result.append(TRANSPARENT)
        else:
            result.append(to_rgb565(r, g, b))
    return result

lines = []
lines.append("#pragma once")
lines.append("// Auto-generated by tools/img_to_h.py — do not edit manually")
lines.append(f"// {NUM_IMAGES} outfits at {SCREEN_W}x{SCREEN_H} RGB565")
lines.append("")
lines.append("#include <Arduino_GFX_Library.h>")
lines.append("")
lines.append(f"static const uint16_t OUTFIT_W = {SCREEN_W};")
lines.append(f"static const uint16_t OUTFIT_H = {SCREEN_H};")
lines.append(f"static const uint16_t OUTFIT_TRANSPARENT = 0x{TRANSPARENT:04X}; // magenta key color")
lines.append("")

for i in range(NUM_IMAGES):
    path = IMG_DIR / f"{i}.png"
    pixels = process_image(path)
    assert len(pixels) == SCREEN_W * SCREEN_H
    hex_vals = ", ".join(f"0x{p:04X}" for p in pixels)
    lines.append(f"// Image {i}")
    lines.append(f"static const uint16_t OUTFIT_{i}[] PROGMEM = {{{hex_vals}}};")
    lines.append("")
    print(f"  processed {path.name}")

lines.append("static const uint16_t* const OUTFITS[] = {")
lines.append("  " + ", ".join(f"OUTFIT_{i}" for i in range(NUM_IMAGES)))
lines.append("};")
lines.append("")
lines.append("// Returns outfit index (0-5) for a temperature in Fahrenheit")
lines.append("static inline uint8_t outfit_index(float tempF) {")
lines.append(f"  if (tempF >= {THRESHOLDS[0]}f) return 0;")
for i, t in enumerate(THRESHOLDS[1:], 1):
    lines.append(f"  if (tempF >= {t}f) return {i};")
lines.append(f"  return {NUM_IMAGES - 1};")
lines.append("}")
lines.append("")
lines.append("// Draw the correct outfit for a temperature (Fahrenheit)")
lines.append("// bgColor: RGB565 background color (default black 0x0000)")
lines.append("// Call after canvas_begin().")
lines.append("static inline void draw_outfit_for_temp(Arduino_GFX* gfx, float tempF, uint16_t bgColor = 0x0000, int16_t x = 0, int16_t y = 0) {")
lines.append("  uint8_t idx = outfit_index(tempF);")
lines.append("  gfx->fillScreen(bgColor);")
lines.append("  gfx->draw16bitRGBBitmapWithTranColor(x, y, (uint16_t*)pgm_read_ptr(&OUTFITS[idx]), OUTFIT_TRANSPARENT, OUTFIT_W, OUTFIT_H);")
lines.append("}")
lines.append("")

OUT_PATH.write_text("\n".join(lines))
print(f"Written {OUT_PATH}")
