#!/usr/bin/env python3
"""
img_to_h.py — converts images/0-5.png to src/outfits.h
Images are scaled to fit 320x240 (landscape), converted to 1-bit bitmaps.
Opaque dark pixels → 1 (draw fg color), transparent/light pixels → 0 (draw bg color).
Storage: 320*240/8 * 6 images ≈ 57 KB (vs ~921 KB for RGB565).

Temperature mapping:
  0 = >78°F   (bikini)
  1 = 69-78°F
  2 = 59-69°F
  3 = 50-58°F
  4 = 39-49°F
  5 = <39°F   (heavy coat)

Usage:
    python3 img_to_h.py
Outputs:
    src/outfits.h
"""

from PIL import Image
from pathlib import Path
import math

SCREEN_W = 320
SCREEN_H = 240
NUM_IMAGES = 6
IMG_DIR = Path(__file__).parent / "images"
OUT_PATH = Path(__file__).parent / "src" / "outfits.h"

# Threshold: alpha >= this AND luminance <= this → foreground (1-bit set)
ALPHA_THRESH = 128
LUMA_THRESH = 128  # pixels darker than 50% grey are considered "ink"

# Temperature thresholds in °F (descending), index into image array
THRESHOLDS = [78.8, 69.8, 59.0, 50.0, 39.2]
# 0: >=78.8  1: 69.8-78.7  2: 59-69.7  3: 50-58.9  4: 39.2-49.9  5: <39.2

def pack_bits(bits):
    """Pack a list of 0/1 ints into MSB-first bytes."""
    result = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bits):
                byte |= bits[i + j] << (7 - j)
        result.append(byte)
    return result

def process_image(path):
    """Return (ink_bytes, skin_bytes) — two packed 1-bit layers."""
    img = Image.open(path).convert("RGBA")
    iw, ih = img.size
    # Scale to fill height, preserve aspect ratio
    scale = SCREEN_H / ih
    new_w = int(iw * scale)
    new_h = SCREEN_H
    img = img.resize((new_w, new_h), Image.LANCZOS)
    if new_w > SCREEN_W:
        scale2 = SCREEN_W / new_w
        img = img.resize((SCREEN_W, int(new_h * scale2)), Image.LANCZOS)
    w, h = img.size
    # Center on blank canvas
    canvas = Image.new("RGBA", (SCREEN_W, SCREEN_H), (0, 0, 0, 0))
    x = (SCREEN_W - w) // 2
    y = (SCREEN_H - h) // 2
    canvas.paste(img, (x, y), img)

    ink_bits = []
    skin_bits = []
    for r, g, b, a in canvas.getdata():
        luma = 0.299 * r + 0.587 * g + 0.114 * b
        opaque = a >= ALPHA_THRESH
        ink_bits.append(1 if (opaque and luma <= LUMA_THRESH) else 0)
        skin_bits.append(1 if (opaque and luma > LUMA_THRESH) else 0)

    return pack_bits(ink_bits), pack_bits(skin_bits)

lines = []
lines.append("#pragma once")
lines.append("// Auto-generated by img_to_h.py — do not edit manually")
lines.append(f"// {NUM_IMAGES} outfits at {SCREEN_W}x{SCREEN_H}, two 1-bit layers (ink + skin, MSB first)")
lines.append(f"// {SCREEN_W}*{SCREEN_H}/8 = {SCREEN_W*SCREEN_H//8} bytes per layer per image")
lines.append("")
lines.append("#include <Arduino_GFX_Library.h>")
lines.append("")
lines.append(f"static const uint16_t OUTFIT_W = {SCREEN_W};")
lines.append(f"static const uint16_t OUTFIT_H = {SCREEN_H};")
lines.append("")

BYTES_PER_IMAGE = SCREEN_W * SCREEN_H // 8

for i in range(NUM_IMAGES):
    path = IMG_DIR / f"{i}.png"
    ink, skin = process_image(path)
    assert len(ink) == BYTES_PER_IMAGE
    assert len(skin) == BYTES_PER_IMAGE
    lines.append(f"// Image {i} — ink layer (dark pixels)")
    lines.append(f"static const uint8_t OUTFIT_{i}_INK[] PROGMEM = {{{', '.join(f'0x{b:02X}' for b in ink)}}};")
    lines.append(f"// Image {i} — skin layer (light/white pixels)")
    lines.append(f"static const uint8_t OUTFIT_{i}_SKIN[] PROGMEM = {{{', '.join(f'0x{b:02X}' for b in skin)}}};")
    lines.append("")
    print(f"  processed {path.name} ({len(ink) + len(skin)} bytes)")

lines.append("static const uint8_t* const OUTFITS_INK[] = {")
lines.append("  " + ", ".join(f"OUTFIT_{i}_INK" for i in range(NUM_IMAGES)))
lines.append("};")
lines.append("static const uint8_t* const OUTFITS_SKIN[] = {")
lines.append("  " + ", ".join(f"OUTFIT_{i}_SKIN" for i in range(NUM_IMAGES)))
lines.append("};")
lines.append("")
lines.append("// Returns outfit index (0-5) for a temperature in Fahrenheit")
lines.append("static inline uint8_t outfit_index(float tempF) {")
lines.append(f"  if (tempF >= {THRESHOLDS[0]}f) return 0;")
for i, t in enumerate(THRESHOLDS[1:], 1):
    lines.append(f"  if (tempF >= {t}f) return {i};")
lines.append(f"  return {NUM_IMAGES - 1};")
lines.append("}")
lines.append("")
lines.append("// Draw the correct outfit for a temperature (Fahrenheit).")
lines.append("// Does NOT clear the background — caller is responsible for that.")
lines.append("// skinColor: body/skin tone (default white). inkColor: outlines/clothing (default black).")
lines.append("// Call after canvas_begin().")
lines.append("static inline void draw_outfit_for_temp(Arduino_GFX* gfx, float tempF, int16_t x = 0, int16_t y = 0, uint16_t skinColor = 0xFFFF, uint16_t inkColor = 0x0000) {")
lines.append("  uint8_t idx = outfit_index(tempF);")
lines.append("  gfx->drawBitmap(x, y, (const uint8_t*)pgm_read_ptr(&OUTFITS_SKIN[idx]), OUTFIT_W, OUTFIT_H, skinColor);")
lines.append("  gfx->drawBitmap(x, y, (const uint8_t*)pgm_read_ptr(&OUTFITS_INK[idx]), OUTFIT_W, OUTFIT_H, inkColor);")
lines.append("}")
lines.append("")

OUT_PATH.write_text("\n".join(lines))
print(f"Written {OUT_PATH}")
