; konsumerdevice - board-agnostic display + keyboard library
; Add your board env below and set BOARD_xxx define accordingly.
; Users only need to #include "canvas.h" and/or #include "keyboard.h".

[env]
framework = arduino
platform = espressif32
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    https://github.com/moononournation/Arduino_GFX

[env:cyd]
board = esp32dev
build_flags =
    -DBOARD_CYD

