; konsumerdevice - board-agnostic display + keyboard library
; Add your board env below and set BOARD_xxx define accordingly.
; Users only need to #include "canvas.h" and/or #include "keyboard.h".

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
upload_speed = 1500000
monitor_speed = 115200
lib_deps =
    moononournation/GFX Library for Arduino@^1.4.9
    olikraus/U8g2@^2.35.19
    https://github.com/PaulStoffregen/XPT2046_Touchscreen

[env:cyd]
board = esp32dev
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_CYD

